[mypy]
python_version = 3.12
pretty = True
show_error_codes = True
ignore_missing_imports = True
follow_imports = skip
check_untyped_defs = True
warn_return_any = True
warn_unused_ignores = True
no_implicit_optional = True
exclude = (?x)(^migrations/|^tests/)
